--Desafio: definindo a chave primária

ALTER TABLE [TABELA DE VENDEDORES] ALTER COLUMN [MATRICULA] CHAR(5) NOT NULL;

ALTER TABLE [TABELA DE VENDEDORES] ADD CONSTRAINT PK_TABELA_DE_VENDEDORES PRIMARY KEY CLUSTERED ([MATRICULA]);


--Desafio: datas e campos lógicos

USE SUCOS_VENDAS
DROP TABLE [TABELA DE VENDEDORES]; 

CREATE TABLE [TABELA DE VENDEDORES](
    [MATRICULA] CHAR(5) NOT NULL PRIMARY KEY CLUSTERED,
    [NOME] VARCHAR(100),
    [CIDADE] VARCHAR(100),
    [PERCENTUAL COMISSÃO] FLOAT NOT NULL,
    [DATA INICIO] DATE NOT NULL,
    [TEM DEPENDENTE] BIT);

INSERT INTO [TABELA DE VENDEDORES]
VALUES
('00239','Alberto de Sá Verneck','São Paulo', 0.08,'2020-06-05',1);

SELECT * FROM [TABELA DE VENDEDORES];


--Desafio: mais um vendedor

INSERT INTO [TABELA DE VENDEDORES]
VALUES
('00240','Marcela Almeida','Rio de Janeiro', 0.07,'2021-01-12','FALSE')
